apiVersion: v1
kind: ConfigMap
metadata:
  name: pr-agent-config
  namespace: {{ include "pr-agent.namespace" . }}
  labels:
    app: pr-agent-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- if .Values.configuration.useExistingConfigMap }}
  # No data will be created if using an existing configmap
  {{- else }}
  # Create configmap data from values.yaml or external file
  configuration.toml: |-
    {{ include "pr-agent.configuration" . | nindent 4 }}
  {{- end }}