{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tenant-{{ .Values.tenant_id }}-httproute
  namespace: {{ include "pr-agent.namespace" . }}
spec:
  parentRefs:
  - kind: Gateway         
    name: {{ .Values.gateway.parentRef.name }}
    namespace: {{ .Values.gateway.parentRef.namespace }}
  hostnames:
  - {{ include "pr-agent.gatewayHost" . | quote }}
  rules:
  - matches:
    backendRefs:
    - name: {{ .Values.service.name }}
      namespace: {{ include "pr-agent.namespace" . }}
      port: {{ .Values.service.port }}
{{- end }} 