{{- if and (eq .Values.storage.type "pvc") .Values.storage.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
  namespace: {{ include "pr-agent.namespace" . }}
spec:
  accessModes:
    {{- range .Values.storage.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.storage.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
  {{- if .Values.storage.pvc.volumeName }}
  volumeName: {{ .Values.storage.pvc.volumeName }}
  {{- end }}
{{- end }}

{{- if and (eq .Values.storage.type "s3-mountpoint") .Values.storage.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "s3-mountpoint-pvc-{{ .Values.tenant_id }}"
  namespace: {{ include "pr-agent.namespace" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-mountpoint-storageclass
  resources:
    requests:
      storage: 100Gi
  volumeName: "s3-mountpoint-pv-{{ .Values.tenant_id }}"
{{- end }} 