{{- if .Values.serviceAccount.create -}}
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jit-agent-service-account
  namespace: {{ include "pr-agent.namespace" . }}

---
# Role with permissions to manage pods and jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager-role
  namespace: {{ include "pr-agent.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]

---
# RoleBinding to bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pr-agent-pod-manager
  namespace: {{ include "pr-agent.namespace" . }}
subjects:
- kind: ServiceAccount
  name: jit-agent-service-account
roleRef:
  kind: Role
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io
{{- end }} 