apiVersion: v1
kind: Secret
metadata:
  name: pr-agent-secrets
  namespace: {{ include "pr-agent.namespace" . }}
  labels:
    app: pr-agent-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.secrets.useExistingSecret }}
  # No data will be created if using an existing secret
  {{- else }}
  # Create secret data from values.yaml
  .secrets.toml: {{ .Values.secrets.secretsToml | b64enc }}
  {{- end }} 